### ISSUE TITLE
angular code generate requirement

### ISSUE THREAD

**Issue by mahedee** [techcombd/academia#56]
```
$ npm install -g @angular/cli
```
Generate module of `Parent` module `App` -

```
$ ng g module classinfo -m App -routing classinfo-routing
```

**Comment by ratanparai** [comment]
I thought intensely and I am not going to write tutorials about how to write code in the form of documentation. There are many good tutorials and if you need more info `Google` is at everyone's fingertips! 

No one can build a good software by following some predefined instruction bliendly. So I am closing this.
