### ISSUE TITLE
Write basic CRUD functionality 

### ISSUE THREAD

**Issue by ratanparai** [techcombd/academia#8]
Write a basic CRUD operation using Angular front-end. 

Need to choose a basic model to implement.

**Comment by mahedee** [comment]
Model: Institution
1. Property should be : Id, Name, Code, Slogan, Address, Email, Web, Logo, Estd
2. Here Id and Name is mandatory field

**Comment by ratanparai** [comment]
This Issue is very big so splitting it into issue #15  and issue #16 as create and view institute is already implemented in PR #14 

I am also closing this issue.
